title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://dyammons.github.io/WORKSHOP_TEST

aux_links:
  Template Repository: https://dyammons.github.io/WORKSHOP_TEST
