title: FACC workshop - Spring 2024
description: A compilation of lessons on general coding topics!
theme: just-the-docs

url: https://dyammons.github.io/WORKSHOP_TEST

aux_links:
  Template Repository: https://github/dyammons/WORKSHOP_TEST

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: false

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# footer_content: ""

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html



# Color scheme currently only supports "dark", "light"/nil (default), or a custom scheme that you define
color_scheme: nil

callouts_level: loud # or quiet
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  tip:
    title: Tip
    color: green
  note:
    title: Note
    color: purple
  warn:
    title: Warning
    color: red