title: CSU coding workshop
description: A compilation of lessons on general coding topics!
theme: just-the-docs

url: https://dyammons.github.io/WORKSHOP_TEST

aux_links:
  Template Repository: https://dyammons.github.io/WORKSHOP_TEST

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: false

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"


# Color scheme currently only supports "dark", "light"/nil (default), or a custom scheme that you define
color_scheme: nil

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red